baseurl: https://gzombify.github.io/
languageCode: ru
theme: hugo-theme-stack
paginate: 5

title: 'ГЗОМ'
copyright: 'Михаил Боде'

languages:
    ru:
        languageName: Русский
        title: ГЗОМ
        weight: 1
        params:
            description: Описание

DefaultContentLanguage: ru
hasCJKLanguage: false
permalinks:
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /static/favicon.png

    footer:
        since: 2016
        customText: Сделано во славу Зализняка и Розенталя добрыми грамотными крепостными.

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 GMT

    sidebar:
        emoji: 🍥
        subtitle: 
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    article:
        math: false
        toc: false
        readingTime: true
        license:
            enabled: false

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10

    opengraph:
        twitter:
            site: gzombify
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Главная
          url: /
          weight: -100
          params:
            icon: home
            newTab: false
        - identifier: about
          name: Что такое «Гзом»?
          url: /chto-takoe-gzom/
          weight: -90
          params:
            icon: mood-puzzled
            newTab: false

    social:
        - identifier: telegram
          name: Telegram
          url: https://t.me/gzombify
          params:
              icon: brand-telegram
        - identifier: facebook
          name: Facebook
          url: https://facebook.com/gzombify
          params:
              icon: brand-facebook
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/gzombify
          params:
              icon: brand-twitter
        - identifier: vk
          name: VK
          url: https://vk.com/gzombify
          params:
              icon: brand-vk

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
